
```python
import numpy as np
import matplotlib.pyplot as plt

def calculate_harmonic_properties():
    """
    Calculates the Orbital Angular Momentum (OAM) and Helicity of the 23rd harmonic
    generated by a sequence of three time-delayed laser pulses.

    The model relies on the conservation laws for single-color HHG:
    1. OAM conservation: l_q = q * l_driver
    2. Helicity conservation: sigma_q = sigma_driver

    Parameters are defined in SI units.
    """

    # --- Constants and Parameters (SI Units) ---
    
    # Physical Constants
    c = 299792458.0          # Speed of light in vacuum (m/s)
    hbar = 1.0545718e-34     # Reduced Planck constant (J*s)
    e_charge = 1.60217663e-19 # Elementary charge (C)

    # Laser Parameters
    wavelength = 800e-9      # 800 nm converted to meters
    omega = 2 * np.pi * c / wavelength # Angular frequency (rad/s)
    
    # Pulse Parameters
    tau_fwhm = 50e-15        # 50 fs pulse duration converted to seconds
    # Note: Pulse timing (delays) determines the sequence of interactions 
    # but the conservation rules for harmonic order q depend only on 
    # the driver's properties at the moment of emission.
    pulse_delays = [0e-15, 30e-15, 60e-15] # [0, 30, 60] fs in seconds

    # Harmonic Order
    q = 23

    # Driving Field Properties (Pulse 1, 2, 3)
    # l: Topological charge (OAM) in units of hbar
    # sigma: Helicity (+1 for LCP, -1 for RCP)
    driver_is = {
        1: {'l': -1, 'sigma': +1, 'color': 'blue', 'label': 'Pulse 1 (t=0)'},
        2: {'l':  2, 'sigma': -1, 'color': 'red',  'label': 'Pulse 2 (t=30)'},
        3: {'l':  1, 'sigma': +1, 'color': 'green','label': 'Pulse 3 (t=60)'}
    }

    results = []

    print(f"{'Source':<20} | {'Driver l':<10} | {'Driver σ':<10} | {'q':<5} | {'Harmonic l':<12} | {'Harmonic σ':<12}")
    print("-" * 85)

    # --- Calculation ---
    
    for pulse_id, props in driver_is.items():
        l_driver = props['l']
        sigma_driver = props['sigma']
        
        # Calculate Harmonic Properties based on Conservation Laws
        # OAM: l_q = q * l_driver
        l_harmonic = q * l_driver
        
        # Helicity: sigma_q = sigma_driver
        sigma_harmonic = sigma_driver
        
        # Store result
        res = {
            'pulse_id': pulse_id,
            'label': props['label'],
            'l_driver': l_driver,
            'sigma_driver': sigma_driver,
            'l_harmonic': l_harmonic,
            'sigma_harmonic': sigma_harmonic
        }
        results.append(res)
        
        # Print row
        sigma_str = 'LCP (+1)' if sigma_harmonic == 1 else 'RCP (-1)'
        print(f"{props['label']:<20} | {l_driver:<10} | {sigma_driver:<10} | {q:<5} | {l_harmonic:<12} | {sigma_str:<12}")

    print("\n" + "="*85)
    print("INTERPRETATION:")
    print("The 23rd harmonic is generated as a superposition of three distinct modes")
    print("corresponding to the three driving pulses in time. Because the pulses are")
    print("temporally separated (time delays >= 30fs), the harmonic emission occurs")
    print("at three distinct times. The OAM and Helicity are conserved individually")
    print("for each interaction.")
    print("="*85)

    # --- Visualization ---
    
    # We visualize the intensity profile of the 23rd harmonic field contributions
    # to illustrate the different OAM states.
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5), subplot_kw={'projection': 'polar'})
    
    # Grid for visualization (normalized radial coordinate r/w0)
    r = np.linspace(0, 2.5, 100)
    phi = np.linspace(0, 2*np.pi, 100)
    R, PHI = np.meshgrid(r, phi)
    
    for i, res in enumerate(results):
        ax = axes[i]
        
        l_q = res['l_harmonic']
        # Amplitude approximation for LG_0^l mode: |E|^2 ~ r^(2|l|) * exp(-2r^2)
        # Note: This is a qualitative visualization of the phase singularity structure.
        Amplitude_sq = (R**(2*abs(l_q))) * np.exp(-2 * R**2)
        
        # Add phase factor for visualization of the vortex structure exp(i * l_phi * phi)
        # We map the complex field to real part for plotting intensity pattern
        # To make the vortex 'arms' visible, we take the square of the amplitude
        # The zeros (donut hole) are characteristic of non-zero OAM.
        
        mesh = ax.contourf(PHI, R, Amplitude_sq, 100, cmap='inferno')
        ax.set_title(f"{res['label']}\nHarmonic Order q={q}\nOAM l = {l_q}, Helicity $\sigma$ = {res['sigma_harmonic']}", va='bottom')
        ax.set_ylim(0, 2.5)
        ax.set_yticklabels([])

    plt.suptitle(f'Intensity Profile (Qualitative) of the {q}th Harmonic Contributions', fontsize=16)
    plt.tight_layout()
    
    # Save figure
    plt.savefig('hhg_23rd_harmonic_oam.png')
    print("\n[INFO] Visualization saved as 'hhg_23rd_harmonic_oam.png'")
    
    return results

if __name__ == "__main__":
    calculate_harmonic_properties()
```