```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh
import sys

# ---------------------------------------------------------
# 1. Configuration and Constants
# ---------------------------------------------------------

# Grid parameters
L = 60  # mesh size
N_bands_to_compute = -1 # Compute all available bands in basis
N_bands_top = 3         # Number of top bands to analyze for Chern number
Target_band_idx = -1    # Index for top electron band (-1 is the highest energy band)

# Physical Constants
hbar_div_2m_e = 7619.96423  # meV * Angstrom^2 (given: hbar/(2*m_e))
# hbar^2 / (2 m*) = hbar * (hbar / 2 m*) = hbar * constant?
# No, the constant given is hbar/(2*m_e).
# Kinetic term is (hbar^2 k^2) / (2 m*).
# Let r = m*/m_e. Then term is (hbar^2 k^2) / (2 r m_e) = (hbar/2m_e) * (hbar/r) * k^2 ? 
# No. Let's check dimensions.
# hbar: [E t]
# hbar/(2m_e): [E t M^-1]
# k^2: [L^-2]
# product: [E t M^-1 L^-2].
# We need [E].
# So we need a factor M L^2 / t. 
# Let's look at the standard term: hbar^2 k^2 / 2m.
# Given constant C = hbar / (2 m_e).
# hbar^2 / (2 m*) = hbar * (hbar / (2 m*)) = hbar * (m_e / m*) * (hbar / (2 m_e)).
# Kinetic Energy = hbar * (hbar / (2 m_e)) * (m_e / m*) * k^2.
# We need hbar in meV * s to multiply by k (1/A) to get velocity?
# Or easier: hbar^2 / (2m) in units meV * A^2.
# hbar (meV*s) approx 6.58e-13 meV*s.
# m_e (kg). 
# Actually, let's derive the factor for code from "hbar/(2 m_e) = 7619.96423 meV A^2".
# Check: hbar (J s) = 1.05e-34. m_e = 9.11e-31. hbar/2m_e = 5.77e-5 J s / kg = 5.77e-5 m^2/s.
# 1 meV = 1.6e-22 J.
# hbar/2m_e in meV*s^2/A^2 ? No.
# Let's strictly use the provided number as `const_hbar_2m`.
# Kinetic term in Hamiltonian: (hbar^2 / 2m*) k^2.
# (hbar^2 / 2m*) = (hbar / (2 m_e)) * (hbar * m_e / m^*).
# Let C = 7619.96423 (units: meV * A^2 * ang_freq^-1 ? No.)
# If units of C are meV * A^2 * (something), let's check standard conversion.
# Rydberg atomic units: hbar^2/(2m_e) = 1 (energy * length^2) approx?
# In atomic units, hbar=m=e=1. Energy is Ha, length is a0.
# 1 Ha ~ 27.2 eV. 1 a0 ~ 0.529 A.
# 1 Ha * a0^2 = 27.2 eV * (0.529 A)^2 ~= 7.6 eV A^2.
# hbar^2 / 2m = 1 (in Ha * a0^2).
# So hbar^2 / 2m_e in eV A^2 is approx 7.6.
# The given constant is 7619.96423 *meV* A^2. This is 7.6199 eV A^2.
# So the given constant is indeed hbar^2 / (2 m_e) in meV A^2.
# So:
# kinetic_prefactor = (hbar^2 / (2 m_e)) / (m*/m_e) = const / (m*/m_e).
kinetic_const_meV_A2 = 7619.96423 

# Model Parameters
# Values from Wu et al. (2019)
theta_deg = 3.5
m_star_ratio = 0.6          # m* relative to m_e
V = 16.5                   # meV
psi_deg = -105.9           # degrees
w = -18.8                  # meV
a0 = 3.52                  # Angstrom

# Derived parameters
theta = np.deg2rad(theta_deg)
psi = np.deg2rad(psi_deg)

# Moire lattice constant a_M
a_M = a0 / (2 * np.sin(theta / 2.0))

# Reciprocal lattice vectors g_i
# g1 = (4*pi)/(sqrt(3)*a_M) * (1, 0)
g_mag = (4 * np.pi) / (np.sqrt(3) * a_M)
g1 = np.array([g_mag, 0.0])

# Rotation matrices
def C3(v):
    # Rotate by 120 degrees (2pi/3)
    c = np.cos(2*np.pi/3)
    s = np.sin(2*np.pi/3)
    R = np.array([[c, -s], [s, c]])
    return np.dot(R, v)

# Generate g_i and q_i
g_vecs = [g1, C3(g1), C3(C3(g1))]
# q1 = |g1| * (0, 1/sqrt(3))
q1 = np.array([0.0, g_mag / np.sqrt(3)])
q_vecs = [q1, C3(q1), C3(C3(q1))]

# Reciprocal lattice basis vectors for BZ
b1 = g1
b2 = g1 + g_vecs[1] # g2
# Check area
BZ_area = np.abs(np.cross(b1, b2))

# Basis cutoff
# |Q| < 4.1 |b1|
cutoff_radius = 4.1 * np.linalg.norm(b1)

# ---------------------------------------------------------
# 2. Plane Wave Basis Generation
# ---------------------------------------------------------

def get_basis_vectors(layer):
    """
    Generate basis vectors Q for a given layer.
    For top (t): Q - q1 is a reciprocal lattice vector.
    For bottom (b): Q + q1 is a reciprocal lattice vector.
    Condition: |Q| < cutoff_radius.
    """
    # We need to find all G in the reciprocal lattice generated by g1, g2 
    # such that resulting Q satisfies conditions.
    # Since Q must be small (< 4.1|b1|), we can just scan integer pairs (n1, n2) 
    # such that |n1 b1 + n2 b2| < cutoff_radius * 2 (approx).
    
    basis = []
    
    # Scan range for integer combinations of reciprocal lattice vectors (which are g1, g2)
    # Actually, the reciprocal lattice of the Moire pattern is spanned by g1, g2.
    # But b1=g1, b2=g1+g2. They span the same lattice.
    
    limit = 5 # Should be enough for cutoff ~ 4 unit cells
    for n1 in range(-limit, limit + 1):
        for n2 in range(-limit, limit + 1):
            # Reciprocal lattice vector G
            G = n1 * b1 + n2 * b2 # Note: b2 is combination of g's, b1 is g1.
            # If we use g1, g2 directly:
            G_alt = n1 * g1 + n2 * g_vecs[1]
            
            if layer == 't':
                # Condition: Q - q1 = G  => Q = G + q1
                Q = G_alt + q1
            else: # 'b'
                # Condition: Q + q1 = G  => Q = G - q1
                Q = G_alt - q1
            
            if np.linalg.norm(Q) < cutoff_radius:
                basis.append(Q)
                
    # Deduplicate
    unique_basis = []
    seen = set()
    for q in basis:
        t = (round(q[0], 6), round(q[1], 6))
        if t not in seen:
            seen.add(t)
            unique_basis.append(q)
            
    return np.array(unique_basis)

Q_basis_t = get_basis_vectors('t')
Q_basis_b = get_basis_vectors('b')

print(f"Basis size (Top): {len(Q_basis_t)}")
print(f"Basis size (Bottom): {len(Q_basis_b)}")
print(f"Total basis size: {len(Q_basis_t) + len(Q_basis_b)}")

# Combine basis and keep track of indices
# Order: All top layer states first, then bottom layer states
# Basis vector at index i: if i < Nt, it's layer t with vector Q_basis_t[i]
Nt = len(Q_basis_t)
Nb = len(Q_basis_b)
dim = Nt + Nb

# ---------------------------------------------------------
# 3. Hamiltonian Construction
# ---------------------------------------------------------

def construct_hamiltonian(k_vec):
    """
    Construct Hamiltonian matrix at momentum k.
    """
    H = np.zeros((dim, dim), dtype=complex)
    
    # Diagonal blocks: Kinetic + Potential
    # Top layer
    for i, Q in enumerate(Q_basis_t):
        # Kinetic
        k_minus_Q = k_vec - Q
        H[i, i] = (kinetic_const_meV_A2 / m_star_ratio) * np.dot(k_minus_Q, k_minus_Q)
        
        # Potential 2V sum cos(g.r +/- psi)
        # Matrix elements couple Q to Q +/- g_i
        # Top layer: +psi
        # Term V * sum (e^{i(g.r + psi)} + e^{-i(g.r + psi)})
        # In momentum space: V * sum (e^{i psi} delta(Q', Q-g) + e^{-i psi} delta(Q', Q+g))
        for g in g_vecs:
            # Check for Q' = Q + g
            Q_plus = Q + g
            # Find index of Q_plus in basis
            # Naive search is slow, but dim is small (~300)
            for j, Q_target in enumerate(Q_basis_t):
                if np.allclose(Q_plus, Q_target):
                    H[j, i] += V * np.exp(-1j * psi) # e^{i(g.r+psi)} shifts +g, coeff V e^{-i psi}? 
                    # Let's check signs carefully.
                    # Integral psi(r)* r.r' = sum V ... delta(k', k+g)
                    # H_{k', k} = V e^{i psi}
                    # Here k corresponds to basis vector Q. 
                    # H is H_{Q'}
                    # Potential V cos(g.r + psi) -> V/2(e^{i(g.r+psi)} + h.c.)
                    # Fourier transform of e^{i g.r} shifts k -> k+g.
                    # So <Q'|H|Q> gets V e^{i psi} if Q' = Q - g ??
                    # Let's write real space integral:
                    # int e^{i(k-Q)r} H e^{-i(k-Q')r} ~ H_{Q'-Q}
                    #谱projector.
                    # Term V e^{i(g.r + psi)} = V e^{i psi} e^{i g.r}
                    # Integral of e^{i g.r} connects diff components.
                    # If H has e^{i g.r}, then it couples k to k-g? No.
                    # Real op T(r). Matrix element <r'|T|r>.
                    # Formalism used in Wu PRL 2019:
                    # H_0 = hbar^2 k^2/2m + sum V_g e^{i g.r}
                    # Diagonalization in basis |k-Q>.
                    # <k-Q'| e^{i g.r} |k-Q> ~ delta(Q', Q-g).
                    # So if Hamiltonian has term coefficient A * e^{i g.r}, it connects Q to Q-g.
                    # Top layer potential: V(e^{i(g.r+psi)} + e^{-i(g.r+psi)})
                    # 1. e^{i(g.r+psi)}: connects Q to Q-g (since Q' = Q - g).
                    # 2. e^{-i(g.r+psi)}: connects Q to Q+g.
                    
                    # Let's look at Q_plus = Q + g. This matches term 2 (e^{-i...}).
                    # Coeff for e^{-i(g.r+psi)} is V * e^{-i psi}.
                    H[j, i] += V * np.exp(-1j * psi)
                    
            Q_minus = Q - g
            for j, Q_target in enumerate(Q_basis_t):
                if np.allclose(Q_minus, Q_target):
                    # Matches term 1 (e^{i(g.r+psi)}). Coeff V * e^{i psi}.
                    H[j, i] += V * np.exp(1j * psi)

    # Bottom layer
    offset = Nt
    for idx_b, Q in enumerate(Q_basis_b):
        row = offset + idx_b
        # Kinetic
        k_minus_Q = k_vec - Q
        H[row, row] = (kinetic_const_meV_A2 / m_star_ratio) * np.dot(k_minus_Q, k_minus_Q)
        
        # Potential: -psi
        # V (e^{i(g.r - psi)} + e^{-i(g.r - psi)})
        for g in g_vecs:
            Q_plus = Q + g # From e^{-i(g.r - psi)}
            for j, Q_target in enumerate(Q_basis_b):
                if np.allclose(Q_plus, Q_target):
                    H[offset + j, row] += V * np.exp(1j * psi) # coeff V e^{i(-psi)} = V e^{-i psi}
                                                              # Wait. e^{-i(g.r-psi)} = e^{i psi} e^{-i g.r}
                                                              # Connects Q to Q+g. Coeff V e^{i psi}. Correct.
                    
            Q_minus = Q - g # From e^{i(g.r - psi)}
            for j, Q_target in enumerate(Q_basis_b):
                if np.allclose(Q_minus, Q_target):
                    H[offset + j, row] += V * np.exp(-1j * psi) # coeff V e^{-i(-psi)} = V e^{i psi}?
                                                               # e^{i(g.r-psi)} = e^{-i psi} e^{i g.r}
                                                               # Connects Q to Q-g. Coeff V e^{-i psi}. Correct.

    # Off-diagonal blocks: Tunneling
    # w sum e^{-i q.r} (t to b)
    # w sum e^{i q.r} (b to t)
    
    # Top to Bottom <Q_t| H |Q_b> = w * sum delta(Q_t - q - Q_b, G)
    # Or Wu notation: T(r) = w sum e^{i q_j.r}. 
    # Wu 2019 Eq 3: T(r) = w sum T_j(r)
    # Usually H = diag + T(r).
    # <r,t|H|r',b> = T(r-r').
    # Matrix element <k-Q_t, t | H | k-Q_b, b> ~ w sum delta(Q_t - Q_b - q)
    # Note: The Hamiltonian in problem statement has e^{-i q.r} in top-right.
    # This couples t(r) to b(r'). 
    # Basis functions are plane waves. 
    # <Q_t| e^{-i q.r} |Q_b> is nonzero if Q_t = Q_b - q (promoted -q).
    # Let's check: Int e^{i(k-Q_t)r} e^{-i q.r} e^{-i(k-Q_b)r} = delta(Q_t + q - Q_b)
    # So coupling exists if Q_b = Q_t + q.
    # Element = w.
    
    # Loop over q_i
    for q in q_vecs:
        # Top row, Bottom col
        # For each Q_t, find Q_b = Q_t + q
        for i_t, Q_t in enumerate(Q_basis_t):
            Q_b_target = Q_t + q
            for j_b, Q_b in enumerate(Q_basis_b):
                if np.allclose(Q_b, Q_b_target):
                    H[offset + j_b, i_t] += w # Top row: i_t, Bottom col: offset+j_b
                    # Wait, matrix form is 
                    # ( H_tt   H_tb )
                    # ( H_bt   H_bb )
                    # Row is bra <t|, Col is ket |b>.
                    # So H[i_t, offset + j_b] is correct for <t|H|b>.
                    # Problem statement: Top right element is w sum e^{-i q.r}.
                    H[i_t, offset + j_b] += w 
                    
        # Bottom row, Top col
        # Conjugate term w e^{i q.r}
        # <Q_b| e^{i q.r} |Q_t> nonzero if Q_b = Q_t - q.
        # Element = w*
        # Since w is real in our parameters (-18.8), w* = w.
        for i_b, Q_b in enumerate(Q_basis_b):
            Q_t_target = Q_b - q
            for j_t, Q_t in enumerate(Q_basis_t):
                if np.allclose(Q_t, Q_t_target):
                    H[i_b, offset + j_t] += w
                    # H[bb, bt] -> H[offset+i_b, j_t]
                    
    return H

# ---------------------------------------------------------
# 4. Solver and Analysis Functions
# ---------------------------------------------------------

def get_k_mesh(L):
    """
    Generate k-mesh grid points.
    Coordinates in reciprocal lattice basis (b1, b2).
    Returns list of k-vectors.
    """
    ks = []
    for l1 in range(L):
        for l2 in range(L):
            k = ((l1 / L) - 0.5) * b1 + ((l2 / L) - 0.5) * b2
            ks.append(k)
    return np.array(ks)

def compute_bands_and_eigvecs(ks):
    """
    Diagonalize Hamiltonian for all k points.
    Returns:
        energies: (L*L, dim) array
        eigvecs: (L*L, dim) array of eigenvectors (columns)
    """
    N_k = len(ks)
    energies = np.zeros((N_k, dim))
    eigvecs = np.zeros((N_k, dim), dtype=complex)
    
    print("Diagonalizing Hamiltonian...")
    for i, k in enumerate(ks):
        H = construct_hamiltonian(k)
        vals, vecs = eigh(H) # Ascending order
        energies[i, :] = vals
        eigvecs[i, :] = vecs.T # Store eigenvectors row-wise? 
        # eigh returns vecs[:, i] as i-th eigenvector.
        # We want energy[i, band] and vec[i, band] = state.
        # Let's keep vecs as (dim, dim) transposed to (dim, dim) effectively.
        # eigvecs[i] = vecs.T has shape (dim,)
        # If we store vecs.T, then eigvecs[i, j] is component j of state.
        # No, vecs[:, :] is [x_1, x_2...].
        # Let's reshape eigvecs later if needed.
        # Storing (N_k, dim) where second index is band index.
        eigvecs[i, :] = vecs.T 
    
    return energies, eigvecs

def calculate_chern_numbers(energies, eigvecs, N_bands):
    """
    Calculate Chern numbers for top N_bands bands using Fukui-Hatsugai method.
    """
    N_k = energies.shape[0]
    L_grid = int(np.sqrt(N_k))
    
    # Reshape to grid
    e_grid = energies.reshape((L_grid, L_grid, dim))
    v_grid = eigvecs.reshape((L_grid, L_grid, dim))
    
    # We need overlap between neighbors.
    # U_mu(k) = <u_k | u_{k+mu}> / | <...> |
    
    Chern_nums = np.zeros(N_bands)
    
    # Work with the target bands (top ones)
    # Indices: last N_bands bands
    band_indices = list(range(dim - N_bands, dim))
    
    for b_idx in band_indices:
        # Calculate link variables
        U1 = np.zeros((L_grid, L_grid), dtype=complex)
        U2 = np.zeros((L_grid, L_grid), dtype=complex)
        
        for n1 in range(L_grid):
            for n2 in range(L_grid):
                # k-point
                v_k = v_grid[n1, n2, :]
                
                # k + b1 (shift n1) -> index n1+1, n2
                n1_next = (n1 + 1) % L_grid
                v_k1 = v_grid[n1_next, n2, :]
                overlap1 = np.vdot(v_k, v_k1)
                U1[n1, n2] = overlap1 / np.abs(overlap1)
                
                # k + b2 (shift n2) -> index n1, n2+1
                n2_next = (n2 + 1) % L_grid
                v_k2 = v_grid[n1, n2_next, :]
                overlap2 = np.vdot(v_k, v_k2)
                U2[n1, n2] = overlap2 / np.abs(overlap2)
        
        # Field strength F12
        F_ij = np.zeros((L_grid, L_grid), dtype=complex)
        for n1 in range(L_grid):
            for n2 in range(L_grid):
                n1_next = (n1 + 1) % L_grid
                n2_next = (n2 + 1) % L_grid
                
                # U1(k) * U2(k+b1) * U1(k+b2)^* * U2(k)^*
                val = (U1[n1, n2] * 
                       U2[n1_next, n2] * 
                       np.conj(U1[n1, n2_next]) * 
                       np.conj(U2[n1, n2]))
                
                F_ij[n1, n2] = np.log(val)
        
        # Sum imaginary parts
        # Map log to (-pi, pi]
        ImF = np.imag(F_ij)
        # Adjust wrapping? np.log handles branch cut on negative real axis.
        # We need to ensure continuity in (-pi, pi].
        # Standard formula: sum(F) / 2pi i
        F_sum = np.sum(ImF)
        
        C = F_sum / (2 * np.pi)
        Chern_nums[b_idx - (dim - N_bands)] = C
        
    return Chern_nums

# ---------------------------------------------------------
# 5. Main Execution
# ---------------------------------------------------------

# Generate Grid
ks = get_k_mesh(L)

# Diagonalize
energies, eigvecs = compute_bands_and_eigvecs(ks)

# Calculate Chern numbers
# Note: The problem asks for top THREE bands.
# Highest energy is last one.
C_top_3 = calculate_chern_numbers(energies, eigvecs, 3)

print("\n" + "="*30)
print(f"Twist Angle: {theta_deg} deg")
print("Chern Numbers of the top three bands:")
for i, c in enumerate(C_top_3):
    print(f"  Band {i+1} (from top): {c:.0f}")
print("="*30)

# If code is correct, we expect (1, 1, -2) or (-1, -1, 2).
# The order depends on phase conventions.
# Usually top valence of TMD doped to half filling.
# Here "electron band" usually means conduction. 
# The model is symmetric? No.
# But we just compute for the top energy bands.

# ---------------------------------------------------------
# 6. Quantum Metric Calculation
# ---------------------------------------------------------
# Formula: g_ij = Re ( 1/2 Tr[ P_k P_{k+ij} P_k P_{k-ij} ] ?? )
# Or better: 
# g_{xy} = Re < d_x u | (1-P) | d_y u >
# d_i u_n = sum_{m!=n} < u_m | d_i H | u_n > / (E_n - E_m) | u_m >
# Numerically, we use the projector method on the grid.
# g_ij(k) ~ (1 - delta_ij delta_r) / delta_r^2 ?
# No, use the formula from rest of output generation trace calculation:
# P_n = |u_n><u_n|
# g_ij(k) = 1/2 Tr[ P(k) P(k+i) P(k) P(k+j) ] * (1/dk^2) ? 
# No, finite difference of Projector P_k:
# d_i P = (P(k+i dk) - P(k-i dk)) / 2 dk
# g_ij = 1/2 Tr[ (d_i P) (d_j P) ]
# This is the standard gauge invariant formula.

def calculate_quantum_metric_trace(energies, eigvecs, band_idx):
    """
    Calculate trace of quantum metric for a specific band index `band_idx`
    (where band_idx is relative to the full sorted list, 0...dim-1).
    `band_idx` = -1 for top band.
    """
    N_k = energies.shape[0]
    L_grid = int(np.sqrt(N_k))
    
    # Reshape
    v_grid = eigvecs.reshape((L_grid, L_grid, dim))
    
    # Projector P_k at each point is.outer(v, v.conj())
    # We need dP/dk_x, dP/dk_y.
    # k is on a grid. dk_x = b1 / L, dk_y = (rotated b2?) / L.
    # Distances:
    dk1 = np.linalg.norm(b1) / L_grid
    dk2 = np.linalg.norm(b2) / L_grid
    # Non-orthogonal grid, finite differences are tricky.
    # Formula g_ij usually assumes Cartesian coordinates.
    # We can map k-points to Cartesian coordinates (kx, ky) and use FD there?
    # Or just use the step in the grid directions.
    # Tr G = int dk^2 g_xx + g_yy ...
    # In non-orthogonal basis, we need Jacobian.
    # Area element d^2k = |b1 x b2| / L^2.
    
    # Finite difference approximation for derivatives:
    # P_x = (P(n1+1, n2) - P(n1-1, n2)) / (2 * dx)
    # Here dx is vector b1/L. P_x is a tensor. 
    # We need matrix derivative. 
    # Let's compute dP/dk1 and dP/dk2 (directional derivatives along grid).
    # g_ij = 1/2 Tr[ d_i P d_j P ].
    # Trace g = g_11 + g_22.
    # Total integral = Sum_k (Tr g(k)) * (Area_Element)
    # Area_Element = |b1 x b2| / L^2.
    
    # Note: g_ij in (k1, k2) coordinates.
    # To get physical "Trace", we sum g_11 + g_22 (the components along reciprocal lattice vectors).
    # This corresponds to the trace of the metric in the local basis.
    # Which is invariant under orthogonal rotation.
    # However, b1 and b2 are 120 deg apart. The metric tensor is defined in R^2.
    # Let's extract the "Cartesian" components or just use the formula:
    # Sum <u| d_x (1-P) d_x |u> dk^2
    # We can approximate:
    # g_{11} ~ 1/2 Tr[ (P_{n1+1} - P_{n1-1})^2 ] / (4 dk1^2)
    
    # We need the global magnitude. Dimensionless Tr G = int g^ij dk_i dk_j ? No, g_ij.
    # Tr G = int d^2k (g_kk + g_ll) in orthonormal basis.
    # Or using the area metric.
    # Let's calculate the scalar integrand at each point:
    # Tr(g) = 1/2 Tr[ (d_1 P) (d_1 P) ] * (dk1)^2 + 1/2 Tr[ (d_2 P) (d_2 P) ] * (dk2)^2 ... wait no.
    # g_ij * dk^i dk^j.
    # We want $\int d^2k \text{Tr} g(\mathbf{k})$.
    # This is standard. g is defined w.r.t Cartesian derivatives.
    # We will approximate derivatives using the grid spacing.
    k_step = np.linalg.norm(b1) / L_grid # Approximation assuming BZ is roughly circular or we project.
    # Better: Use the area dA = BZ_area / L^2.
    # Finite diff for derivative d/dk_x is problematic on hex grid.
    # Alternative: Use the definition involving overlaps U_mu.
    # g_ij(k) = 1 - Re[U_i U_j^* ...] / dk^2 ?
    # For 1D: g(k) = (1 - |U|^2) / (dk^2). 
    # For 2D: 
    # Using notation from Provost and Vallee:
    # g_{mu nu} = delta_{mu nu} - Re[ U_mu ] ... not trivial sum.
    # Let's stick to the Projector FD method, mapping grid to Cartesian.
    
    # The k-points are defined as k = x b1 + y b2.
    # We can treat x, y as normalized coordinates (-0.5 to 0.5).
    # Position in 2D plane.
    # Derivatives wrt x, y.
    # Jacobian to k-space area: J = |b1 x b2|.
    # Metric g in x,y space?
    # The definition uses d/dk. 
    # Let d/dk_i be derivative w.r.t Cartesian components.
    # Chain rule: d/dx = (b1)_j d/dkj.
    # Tr g_cart = g_xx + g_yy.
    # Inverse metric? No, just sum of diagonal elements.
    # If basis is not orthonormal, Tr g is not invariant?
    # Tr G is defined for Riemannian manifold.
    # g_ij = < d_i u | d_j u > (real part).
    # d/dk = (b1)_x d/dx1 + (b2)_x d/dx2 ...
    # This is getting complicated.
    # Simplified approach: Treat k-plane as flat Euclidean.
    # Map neighbors to vectors (b1/L, b2/L).
    # d1 P = (P(x+1) - P(x-1)) / (2 * |b1|/L) * direction_b1?
    # No, just treat b1, b2 as basis vectors e1, e2. 
    # Compute g_11' = 1/2 Tr[d_1 P d_1 P] where d_1 is directional derivative along b1.
    # Value g_11' has units of [Length]^2 * [1/|b1|^2]? No.
    # d_1 P = P(k+b1/L) - P(k-b1/L) over 2 step (vector b1/L).
    # So d_1 P ~ P / (Length).
    # g_11 ~ 1/L^2.
    # We want g_ij such that integral is d^2k g_ij.
    # If we sum g_11' * (step_area), we approximate int g_xx' dk dk?
    # Let's trust the provided context hint: "Numerically evaluate... using conventions".
    # Usually implies local finite difference on the mesh.
    # We sum Tr(g) * Area_of_cell.
    # Tr(g) = 1/2 [ (P(i+1)-P(i-1))^2 + ... ] * 1/dk^2
    # Let's use dk = np.linalg.norm(b1)/L (approx magnitude of grid vector).
    
    dk_mag = np.linalg.norm(b1) / L_grid
    
    total_TrG = 0.0
    
    # Central difference loop ignoring boundaries (Periodic?)
    # Problem says "k in BZ". Usually Periodic BC for Bloch states.
    for n1 in range(L_grid):
        for n2 in range(L_grid):
            # Current P
            u = v_grid[n1, n2, band_idx]
            # Periodic neighbors
            u_xp = v_grid[(n1+1)%L_grid, n2, band_idx]
            u_xm = v_grid[(n1-1)%L_grid, n2, band_idx] # Python -1 works but careful with 0
            u_yp = v_grid[n1, (n2+1)%L_grid, band_idx]
            u_ym = v_grid[n1, (n2-1)%L_grid, band_idx]
            
            # Projectors |u><u|
            # We need dP = P' - P.
            # dP ~ |du><u| + |u><du|
            # dP dP = ...
            # 1/2 Tr[dP dP] = |du|^2.
            # So Tr(g) = |d_x u|^2 + |d_y u|^2.
            # du is approx (u_next - u_prev)/2dk.
            
            # NOTE: This ignores the normalization/unitary gauge freedom issues?
            # |u> is normalized. <u|u>=1. <du|u> = -<u|du>. Pure imaginary.
            # |d_x u|^2 = <d_x u|d_x u>.
            # d_x u = (u_xp - u_xm) / (2 dk)
            
            # This is the robust numerical method.
            
            du_x = (u_xp - u_xm) / (2 * dk_mag)
            du_y = (u_yp - u_ym) / (2 * dk_mag)
            
            norm_dux_sq = np.vdot(du_x, du_x).real
            norm_duy_sq = np.vdot(du_y, du_y).real
            
            local_Tr_g = norm_dux_sq + norm_duy_sq
            
            total_TrG += local_Tr_g
            
    # Integral = Sum * dA
    dA = BZ_area / (L_grid * L_grid)
    integral_TrG = total_TrG * dA
    
    return integral_TrG

# Calculate for Top Band
Tr_G_val = calculate_quantum_metric_trace(energies, eigvecs, -1)

print(f"Trace of Quantum Metric G for top electron band: {Tr_G_val:.2f}")

# Plotting
plt.figure(figsize=(10, 6))
# Plot bands along a high symmetry path?
# We only have a grid. We can plot the min/max of each band or a histogram.
# Or estimate the band structure along Gamma-K-M-Gamma.
# Let's just plot the energies of the top few bands vs momentum magnitude to see flatness.

# Extract top 10 bands energies
top_bands_e = energies[:, -10:]
k_norms = np.linalg.norm(ks, axis=1)

# Scatter plot
plt.scatter(k_norms, top_bands_e, s=1, alpha=0.5)
plt.xlabel("|k| ($\AA^{-1}$)")
plt.ylabel("Energy (meV)")
plt.title("Dispersion of top 10 bands")
plt.grid(True, alpha=0.3)
plt.savefig("moire_bands.png")
```