def listModels() -> None:
    # all available methods SAIA can use
    from src.wrappersCrewAi.aiAccess.openAiClient import OpenAiClient
    saia = OpenAiClient()
    print(saia.listModels()) # prints the list of available models from the AI service

def crew1BlackHole() -> None:
    # an example workflow for an autogenerated AI example (Copilot), just tests the crew orchestration with a simple problem
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew1Execute(problemExamples.blackHoleEffect())
    print (result)

def crew2EdelsteinEffectNoSimulation() -> None:
    # uses a crew with more agents then crew1, which is supposed to lead to better result; Works on the discussed modeling request for the Edelstein effect in Kramers-Weyl ferminons; no simulation
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew2Execute(problemExamples.edelsteinEffectNoSimulation())
    print ("\n NEWRUN OF WORKLOW: SIMPLE EDELSTEIN EFFECT (NO SIMULATION)")
    print (result)
    #for me, this resulted in a direct understandig of the Edelstein effect in Kramers-Weyl fermions, instead of a model reduction

def crew2EdelsteinEffectWithSimulation() -> None:
    # same as crew2EdelsteinEffectNoSimulation but with simulation; this is supposed to lead to a better understanding of the problem, but it is also more computationally expensive and time consuming
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew2Execute(problemExamples.edelsteinEffectWithSimulation())
    print ("\nNEWRUN OF WORKLOW: SIMPLE EDELSTEIN EFFECT (WITH SIMULATION)")
    print (result)

def crew4Test() -> None:
    # a more complex workflow with more agents, which is supposed to lead to an even better result; works on the same problem as crew2EdelsteinEffectWithSimulation, but with more agents and a more complex workflow; this is supposed to lead to a better understanding of the problem, but it is also more computationally expensive and time consuming
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew4Execute(problemExamples.edelsteinEffectResourceGathering())
    print (result)

def goldPriceTest() -> None:
    # a workflow to test the ability of the crew to access real sources and provide real information; this is supposed to be a simple test to check if the crew can access the internet and provide real information, which is important for the performance of the crew in solving real problems
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew5Execute(problemExamples.goldPrice())
    print (result)

def dateTest() -> None:
    # a workflow to test the ability of the crew to access real sources and provide real information; this is supposed to be a simple test to check if the crew can access the internet and provide real information, which is important for the performance of the crew in solving real problems
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew6Execute(problemExamples.date())
    print (result)

def toolCheck() -> None:
    # a workflow to test if the crew can access the webSearch tool and provide an example of how to use it to solve a problem; this is important to check if the crew can use the tools that are provided to it, which is important for the performance of the crew in solving real problems
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew7(problemExamples.toolCheck())
    print (result)

if __name__ == "__main__":
    #listModels()
    #crew1BlackHole()
    #crew2EdelsteinEffectNoSimulation()
    #crew3EdelsteinEffectWithSimulation()
    #crew4Test()
    goldPriceTest()
    #dateTest()
    #toolCheck()