def listModels() -> None:
    # all available methods SAIA can use
    from src.wrappersCrewAi.aiAccess.openAiClient import OpenAiClient
    saia = OpenAiClient()
    print(saia.listModels()) # prints the list of available models from the AI service

def crew1BlackHole() -> None:
    # an example workflow for an autogenerated AI example (Copilot), just tests the crew orchestration with a simple problem
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew1Execute(problemExamples.blackHoleEffect())
    print (result)

def crew2EdelsteinEffectNoSimulation() -> None:
    # uses a crew with more agents then crew1, which is supposed to lead to better result; Works on the discussed modeling request for the Edelstein effect in Kramers-Weyl ferminons; no simulation
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew2Execute(problemExamples.edelsteinEffectNoSimulation())
    print ("\n NEWRUN OF WORKLOW: SIMPLE EDELSTEIN EFFECT (NO SIMULATION)")
    print (result)
    #for me, this resulted in a direct understandig of the Edelstein effect in Kramers-Weyl fermions, instead of a model reduction

def crew2EdelsteinEffectWithSimulation() -> None:
    # same as crew2EdelsteinEffectNoSimulation but with simulation; this is supposed to lead to a better understanding of the problem, but it is also more computationally expensive and time consuming
    import problems.problemExamples as problemExamples
    import preparedCrews.simpleCrews as simpleCrews

    result = simpleCrews.crew2Execute(problemExamples.edelsteinEffectWithSimulation())
    print ("\nNEWRUN OF WORKLOW: SIMPLE EDELSTEIN EFFECT (WITH SIMULATION)")
    print (result)


if __name__ == "__main__":
    #listModels()
    #crew1BlackHole()
    crew2EdelsteinEffectNoSimulation()
    #crew3EdelsteinEffectWithSimulation()