gathering_task:
  description: >
    find 3-6 relevant papers for {aim}. One of the papers should be very recent
  expected_output: >
    a list with the important sources: arxivID, Author, date, url, short summary.
    Sort the sources by relevance. MARKDOWN format.
  agent: source_gatherer
