information_extractor:
  role: >
    download papers
  goal: >
     download the papeer at this source: (https://arxiv.org/pdf/2503.20712v1).
     Always call arxiv_paper_fetcher_and_downloader with:
     download_pdf=True,
     output_dir="/absolute/path/arxiv_papers",
     use_title_as_filename=True
  backstory: >
    we want to extract important infor from the arxiv