extraction_task:
  description: >
    download paper from (https://arxiv.org/pdf/2503.20712v1)
    Always call arxiv_paper_fetcher_and_downloader with:
     download_pdf=True,
     output_dir="/absolute/path/arxiv_papers",
     use_title_as_filename=True
  expected_output: >
    steps that where taken and whether download succeeded
  agent: information_extractor