import openai
import sys

class OpenAiClient:
    '''this class handles the interaction with the OpenAi API'''
    def __init__(self) -> None:
        import os
        from dotenv import load_dotenv
        from pathlib import Path
        env_path = Path(__file__).resolve().parent.parent.parent.parent / ".env" # set the path to the .env file
        load_dotenv(dotenv_path=env_path)
        apiKey = os.getenv("API_KEY") # read the API_KEY from the .env file
        self.client = openai.OpenAI( # sets client as an instance of OpenAI class
            api_key=apiKey, # api key is required to authenticate with the OpenAi API
            base_url="https://chat-ai.academiccloud.de/v1"
        )

    def run(self, model: str, messages: dict, **kwargs) -> str:

        #messages = kwargs.get("messages", [])

        context = str(kwargs.get("context", "")) #NOT OPENAI SUPPORTED
        tools = (kwargs.get("tools", [])) # what the agent can use to solve the task, could be python IDE, search engine, ...
        available_functions = str(kwargs.get("available_functions", [])) # NOT OPENAI SUPPORTED

        temperature = float(kwargs.get("temperature", 0.1)) # form 0.0 to 1.0 higher values := more creativity and more randomness 
        max_tokens = int(kwargs.get("max_tokens", 260000)) # max number of tokens to use in entire conversation
        stop = str(kwargs.get("stop", None)) # stop immediately when the model outputs this string
        response_format = str(kwargs.get("response_format", "text")) # can be "text", "json", "xml", etc. depending on the use case and the capabilities of the connected AI; can also be a custom function that processes the raw response from the AI and formats it accordingly; not implemented yet

        stream = bool(kwargs.get("stream", False)) # whether to stream the response from the AI or not (output while generated, no buffer); not implemented yet
        callbacks = kwargs.get("callbacks", []) # callbacks for different stages of the LLM's reasoning process, e.g. before/after API call, before/after response processing, NOT OPENAI SUPPORTED


        #self.__init__() # re-initialze the client to avoid it has not been done before; NOT NEEDED, for now its working without it
        response = self.client.chat.completions.create(
            messages=messages,
            model = model,
            tools=tools,
            temperature=temperature,
            max_tokens=max_tokens,
            stop=stop,
            response_format={"type": response_format},
            stream=stream,
            )

        return {
            "content" : response.choices[0].message.content, # response content generated by the AI
            "usage" : response.usage # token usage information
        }