gathering_task:
  description: >
    find at least 3 relevant papers for {aim}. One of the papers should be very recent
  expected_output: >
    a list with the important sources: arxivID, Author, date, url, short summary.
    Sort the sources by relevance. MARKDOWN format.
  agent: source_gatherer

extraction_task:
  description: >
    Extract relevant information from scientific papers that allow for: {aim}.
  expected_output: >
    All necessary information for building the model.
    Correct citation for the provided information.
    MARKDOWN format with $...$ and $$...$$.
  agent: information_extractor

simple_modelling_task:
  description: >
    create a model that accomplishes: {aim}
    give a mathematical description and explain your steps.
  expected_output: >
    A complete matematical description with textual explainations.
    MARKDOWN format with $...$ and $$...$$. No code.
  agent: simple_modeller

unit_checking_task:
  description: >
    Determine the units off all quantities used in the model. Be aware, that papers might not use SI units.
    Find a correct and consistent unit system for the model build.
    Determine sensible starting parameters for the model and sensible units for them.
  expected_output: >
    A table containing all properties used and their units.
    A description of the choosen unit system.
    Starting parameters.
    . MARKDOWN format with $...$ and $$...$$.
  agent: unit_checker

physician_simulation_task:
  description: >
    Implement the model accurately. Do not alter formulas or calculations but implement them.
    Use the units and unit system determined by the unit_checking_task.
    Create graphics when it is sensible.
  expected_output: >
    Pyhton code that implements the model. The code should output what is asked for: {aim}
  agent: simulation_physician

simulation_correction_task:
  description: >
    Correct bugs in the code. Ensure the final code is running and correct.
    Make sure to not change the calculations.
    Improve coding style and efficiency as long as the calculations remain unaffected.
  expected_output: >
    Executable code without bugs. All content that is not code should be in comments.
  agent: simulation_correcter
